<?php

namespace AppBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function category(){
        $query = $query = $this->getEntityManager()->createQuery('SELECT DISTINCT p.category FROM AppBundle:Book p');
        return $query->getResult();
    }
}
