<?php

namespace AppBundle\Repository;

/**
 * HistoricalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricalRepository extends \Doctrine\ORM\EntityRepository
{
    public function lastid($id){
        $query = $this->getEntityManager()->createQuery('SELECT * FROM AppBundle:Historical where book_id = :id ORDER BY id DESC LIMIT 1');
        $query->setParameters(array(
            'id' => $id,
        ));
        return $query->getResult();
    }
}
